### ISSUE TITLE
Gisto 0.2.6b: Ability for search to search all gist text

### ISSUE THREAD

**Issue by MyITGuy** [Gisto/Gisto#100]
By default, search only searches gist titles and the text of any gist that was highlighted after Gisto was opened.

This becomes a problem when you have several hundred gists. Being able to search all text would be extremely helpful.

This can be recreated by creating two gists with the same text in them, like the word "findme". Close Gisto. Open Gisto (do not select any gist). Enter the text in the search field. The text will not be found in any gist. Highlight the first gist. Search again. It will find one, but not the other.

**Comment by AStupidBear** [comment]
+ 1 for this feature

**Comment by amerzafar** [comment]
i think gisto still does not have these feature? it was requested in 2014
