### ISSUE TITLE
Gisto crashes upon first run

### ISSUE THREAD

**Issue by sanusart** [Gisto/Gisto#135]
Gisto crashes upon first (ever) run. Seems like the cause is recent changes to settings and their defaults.

**Comment by ArchieT** [comment]
Here is a screenshot: ![Screenshot](http://i.imgur.com/DeBq9ba.png)

**Comment by sanusart** [comment]
Cool. Screenshot won't hurt.

**Comment by sanusart** [comment]
Looks like no errors in latest nightlies.

http://build.gistoapp.com/20150110/
http://build.gistoapp.com/20150109/

Need to test more.

**Comment by sanusart** [comment]
Looks like resolved. I guess it was traces of track.js that triggered the crush.
