### ISSUE TITLE
Gisto supports .markdown, .html, but not .asciidoc syntax highlighting

### ISSUE THREAD

**Issue by nancym** [Gisto/Gisto#142]
I'd like to use Gisto to edit and update AsciiDoc-formatted gists, but I'm not seeing syntax highlighting in .asciidoc or .adoc files. I tested Gisto with .html and .markdown files and syntax highlighting works in those. On GitHub .asciidoc and .adoc files are syntax highlighted. It would be great if Gisto supported this. Thanks!

**Comment by sanusart** [comment]
@nancym Will be available in the next release. You may also see it in the automatically build nightly: http://build.gistoapp.com/20150125/

**Comment by nancym** [comment]
Wow, thanks for the quick response! From looking at https://github.com/github/markup it seems that GitHub interprets .asciidoc, .adoc, and .asc extensions as AsciiDoc files, but I'm not sure. I asked about this in a tweet and will let you know what I find out.

I have questions about installing a Gisto nightly build, which I've never done before:

* On 64-bit Windows 7, should I install win-x64 or win-ia32? I usually install 32-bit apps because they seem to work better on my wimpy machine, but I wonder what you recommend.

* On OSX Mavericks, should I install osx-x64 or osx-ia32?

Thanks!

**Comment by sanusart** [comment]
Hey @nancym 
for Windows 7 64-bit you should install `x64`.
As far as I know OSX Mavericks is `x64` too.
