### ISSUE TITLE
Can you be more explicit about the search possibilities ?

### ISSUE THREAD

**Issue by dacoul** [Gisto/Gisto#148]
Hi,

Can you be more explicit about the search possibilities ?

For example 
 - is "multi tags search" possible ?
 - can we mix tag and text search ?
 - regexp ?

Thanks for your work.
Regards
David

**Comment by morsdyce** [comment]
Hi,

Currently the search is a full text search on the gist object which means multi tag, description, filenames and content.

Note that content is currently only working if the gist has been loaded in that session (we are working on offline capability which will allow text search in all gists).
