### ISSUE TITLE
FEATURE add indent options

### ISSUE THREAD

**Issue by ryanpcmcquen** [Gisto/Gisto#156]
I would love to see 2 spaces as an option, it appears that 4 spaces is the default.

**Comment by ryanpcmcquen** [comment]
You guys rock! Thanks!

**Comment by sanusart** [comment]
Left 4 spaces as default as it looks like more generic concept that 2.
You can use a [nightly](http://build.gistoapp.com/latest/) to use this feature until the next release.

**Comment by ryanpcmcquen** [comment]
Excellent!
