### ISSUE TITLE
Allow to choose defaults for public or private for new gists via settings

### ISSUE THREAD

**Issue by sanusart** [Gisto/Gisto#157]
As suggested by @ryanpcmcquen, allow to choose defaults for public or private for new gists via settings.

**Comment by ryanpcmcquen** [comment]
Thanks for adding this, Gisto is the best!!!

**Comment by sanusart** [comment]
So it is like that now:

![image](https://cloud.githubusercontent.com/assets/267718/7103105/3c83fc18-e0a0-11e4-8680-ec7670271d9b.png)

**Comment by ryanpcmcquen** [comment]
Beautiful!
