### ISSUE TITLE
FEATURE add a link to RAW url next to GIST ID, GIST URL

### ISSUE THREAD

**Issue by ryanpcmcquen** [Gisto/Gisto#158]
I'm not entirely clear on the syntax or else I would put together a pull request, but it would be nice to get the raw url (it can be useful for sharing or sourcing files inside other gists/projects).

Thanks!

**Comment by sanusart** [comment]
Cool. Just not sure what icon will suite the best. I was thinking about [fa-code](http://fortawesome.github.io/Font-Awesome/icon/code/)

**Comment by ryanpcmcquen** [comment]
Looks great!

**Comment by morsdyce** [comment]
It's probably the only suitable icon. I've tried fa-file-code-o but it looks a bit crammed so fa-code might be the better choice.

![screenshot 2015-04-09 10 02 14](https://cloud.githubusercontent.com/assets/1665570/7061861/a68bebc8-de9f-11e4-9cbe-023540a46450.png)

**Comment by ryanpcmcquen** [comment]
Also, if possible, use the shortened version of the link:

Long version:
https://gist.githubusercontent.com/ryanpcmcquen/65add2de2d63e9db7208/raw/d7f9d7e4cc0a53d97aaf07e4af28fa47cb8b2046/donuts.php

Short version:
https://gist.githubusercontent.com/ryanpcmcquen/65add2de2d63e9db7208/raw/donuts.php

**Comment by sanusart** [comment]
Closing via 784937a
Currently the best way to get the raw URL to file is to use the URL exactly as API provides it. This wont brake Gisto for enterprise users.

**Comment by ryanpcmcquen** [comment]
Sounds good! Modifying the link is easy enough if needed. :+1:
