### ISSUE TITLE
Make a windows portable version

### ISSUE THREAD

**Issue by jatubio** [Gisto/Gisto#159]
It would be great to have a portable version for Window :)

**Comment by sanusart** [comment]
@jatubio Portable as of "No installer, just click and run" or "No traces on host computer and all that"?

**Comment by jatubio** [comment]
@sanusart  "No installer" would be great, "No traces" would be wonderful ;)

I have tested a "No installer" version and seems to work ok in my Windows 7

**Comment by sanusart** [comment]
@jatubio Yes no insllaer just works (the installer is only for ease). Gisto nightly builds for Windows for example - comes with no installer.

Regarding no traces - we need to check options to apply chromium flag for saving app data in the directory Gisto is running from.

**Comment by sanusart** [comment]
@jatubio I tested with Windows and it seems that by doing the following works:

- Download Windows nightly from [http://build.gistoapp.com/latest/](http://build.gistoapp.com/latest/)
- Extract it to some directory of your choosing
- Create empty file in that directory called `gisto.bat`
- Add the following to this file `gisto.exe --data-path="."`

Start Gisto by double-clicking the `gisto.bat` file - all data will be in this directory you are running Gisto from.

**Comment by jatubio** [comment]
@sanusart, thanks a lot!!

I have put your information on a wiki page. Hope it's ok :)

https://github.com/Gisto/Gisto/wiki/Portable-version-for-windows

**Comment by sanusart** [comment]
Hey @jatubio, we actually don't use the GitHubs wiki, Instead I've updated the FAQ section of Gisto website: http://www.gistoapp.com/faq/#run-as-portable

Thanks

**Comment by jatubio** [comment]
I was surprised that the wiki was so empty ;)
