### ISSUE TITLE
0.3.1 release checklist

### ISSUE THREAD

**Issue by sanusart** [Gisto/Gisto#169]
- [x] make sure BugSnag set to 'Production' mode.
- [x] update changelog
- [x] update site

**Comment by sanusart** [comment]
Closing via 60d564e9903f23dc2a990f361cc321890fe9ce8b

**Comment by ryanpcmcquen** [comment]
Thank you! Updated for SlackBuilds :+1:

http://slackbuilds.org/cgit/slackbuilds/commit/?id=a7c62e2a8

**Comment by sanusart** [comment]
@ryanpcmcquen :+1:
