### ISSUE TITLE
Allow code format for HTML, CSS, JS, JSON and more if possible.

### ISSUE THREAD

**Issue by sanusart** [Gisto/Gisto#171]
Allow code format for HTML, CSS, JS, JSON and more if possible.

HTML, CSS and JS - can be done with [js-beautify](https://github.com/beautify-web/js-beautify)
```
js_beautify(src);
css_beautify(src);
html_beautify(src);
```
JSON - can be done with `JSON.stringify()`

**Comment by morsdyce** [comment]
Isn't this already covered by ace?

**Comment by sanusart** [comment]
No AFAIK. 
Is it?

**Comment by sanusart** [comment]
How shall it be triggered? By "tidy" button or by default with option to turn on/off in settings?

**Comment by morsdyce** [comment]
Apparently it isn't. 
I think it should be by a button

**Comment by sanusart** [comment]
Cool. I thought so too. I have almost finished. Will commit to feature
branch today or the day after and we'll test.
