### ISSUE TITLE
Creating second file and renaming fails

### ISSUE THREAD

**Issue by vmuriart** [Gisto/Gisto#174]
To replicate:
```
Use an existing Gist (mine has only 1 at the moment)
Create a new file on it
Rename the file
add content
Save
Errors with "You cannot save an empty file"
```

But if you instead do.
```
Use an existing Gist (mine has only 1 at the moment)
Create a new file on it
Add content
Save
Rename file
Save
```
This works.

**Comment by morsdyce** [comment]
Thanks for the detailed issue, we'll check it out.

**Comment by sanusart** [comment]
@vmuriart 
I can not reproduce the bug on latest version (0.3.1). 
Can you elaborate what Gisto version on what platform please?

**Comment by vmuriart** [comment]
Version 0.3.1
Windows 8.1 64-bit
Github Enterprise

**Comment by sanusart** [comment]
Thanks

**Comment by vmuriart** [comment]
Hopefully these help. 

Starting point:
![image](https://cloud.githubusercontent.com/assets/13303020/9265084/04a16ea8-41e3-11e5-8308-82ab7823ff2a.png)

This one works (name wasn't changed before saving with content):
![image](https://cloud.githubusercontent.com/assets/13303020/9265098/344ce074-41e3-11e5-8d87-5e31d60ea325.png)

This one fails (name changed before saving with content):
![image](https://cloud.githubusercontent.com/assets/13303020/9265100/44f7e694-41e3-11e5-88a0-7388a2543ae6.png)

**Comment by morsdyce** [comment]
Hi,

We are not able to reproduce this bug on public github or github enterprise. Do you still experience this bug?

P.S sorry for the long delay, been busy with life and work.

**Comment by sanusart** [comment]
Hey @vmuriart,

Maybe you can try with latest [nightly](http://build.gistoapp.com/latest/)?

**Comment by vmuriart** [comment]
@morsdyce. No worries, life happens. Just tried it with the version I have, bug still present. (and i have reset my machine a few times between then and now).

@sanusart Just tried the nightly. I may be doing something wrong, but the content of my `gist`s don't load. Since the content (or the space where i can put content) isnt loading, i can't add anything to them before i try to save. 

I'll try to replicate it on another machine of mine. Ill report back soonish

**Comment by vmuriart** [comment]
@sanusart On the second machine, it displays the content without any issues on the nightly. But the saving bug is still present

**Comment by morsdyce** [comment]
@vmuriart can you describe the content issues you had with the editor, it might be part of the issue.
According to github api if a file is specified with null it should be deleted and our bug tracker shows an error with trying to delete a non existent file.

**Comment by vmuriart** [comment]
@morsdyce the case i described in which i my gists didnt load, and i couldnt add content to a newly created file? 

This is what im seeing 
![image](https://cloud.githubusercontent.com/assets/13303020/9569795/a0077f96-4f2a-11e5-9835-de811d4f19c9.png)

**Comment by morsdyce** [comment]
@vmuriart does the rename bug occur after you cannot see the content? 
do you navigate away from the page and back to see it updated with the content and then try to update it?

Maybe if you could record a gif of your actions because we're both trying to reproduce and not succeeding, yet we see the error in our bug tracker.

**Comment by vmuriart** [comment]
is there a gif recorder you recommend? After the bug occurs (on the stable release) Gist box goes haywire and its hard to get it back to normal.

**Comment by morsdyce** [comment]
http://www.cockos.com/licecap/ works well for me

**Comment by vmuriart** [comment]
![stable](https://cloud.githubusercontent.com/assets/13303020/9569875/ed25032c-4f2d-11e5-8d5e-06137b5e05a9.gif)

This is for the latest stable version

**Comment by vmuriart** [comment]
![nightly](https://cloud.githubusercontent.com/assets/13303020/9569888/6be7b81c-4f2e-11e5-8bbe-e924cab66886.gif)

This is the nightly.

**Comment by morsdyce** [comment]
@vmuriart sorry to drive you crazy with all these tests, but I have 1 final request.

I noticed you have the status bar editor plugin enabled. I tried turning it on just now and noticed there are issues with it, can you try turning it off and then trying to rename a file?

If this still does not work I'll add more validations before sending to github which might resolve the issue without being able to reproduce it.

P.S Thanks for all your help in trying to solve this :)

**Comment by vmuriart** [comment]
No worries, thank you for addressing the bug. Disabling the status bar gave me the editor back on the nightly. But the saving issue is still present. :(

![nightly2](https://cloud.githubusercontent.com/assets/13303020/9569942/1ddd1f34-4f30-11e5-806f-66576c04bc25.gif)

**Comment by vmuriart** [comment]
Though, I'm curious why you can't reproduce the error. Looks like something, somewhere, isn't updating the content of the file, or its trying to submit the wrong file. 
Are there any external dependencies required for the software to run? Perhaps I'm using a buggy version.

**Comment by morsdyce** [comment]
It's most likely and issue with data binding, where when you change the name of the file it creates a new key in the data instead of updating the existing one.

In windows there aren't any external dependencies as its all packed with the application.

I will try to add additional validation and cleanup before submitting to the api and hope it will work, I will update you when i'll have a build ready.

**Comment by morsdyce** [comment]
@vmuriart I published a new build if you could please check it.

You can get it at http://build.gistoapp.com/

Thanks!

**Comment by vmuriart** [comment]
Just gave it a try and still the same error :(

**Comment by morsdyce** [comment]
@vmuriart Ok, so I guess it wasn't the issue I thought it is (I tried to blindly fix it).

I've made another build, please note that this build will also send the content of your gists so I can see how data is being sent and understand what is going on.
So please don't update any sensitive data on it as it will be sent to our bug tracker.

As before you can get it at http://build.gistoapp.com/

Please download that build and reproduce the error, hopefully I will understand more after this.

Thanks

**Comment by vmuriart** [comment]
Ran it a couple times, hopefully that has the info you need.

**Comment by vmuriart** [comment]
Took a glance at the code, idk if any of this will help. 
When a new file is created, it calls  `$scope.addFile` correct?. The empty object is being added to the array with the generic `newfile`. Then it looks like `.update` calls to cycle through the objects it is coming about the `newfile`. Since I edited the name, the object is now being added in line 486 with a `newname`, but the original `newfile` is still in the arrow but with no content in it. Then in line 500 it encounters this and it yells at me. :( this is from the singleContorller.js file.

**Comment by morsdyce** [comment]
That makes allot of sense, in essence the filename property is supposed to override the key name in the object, it must be hitting some bug in the enterprise api and since we are not on the same version of enterprise I was not able to reproduce.

I've added a fix for that and started a new build, it should be ready in about 5 minutes.

**Comment by morsdyce** [comment]
@vmuriart build finished, you may download and check. crossing my fingers!

**Comment by vmuriart** [comment]
Well thats the thing that i was trying to figure out. From tracing the code, it looks like the abort should be happening even before any call is made to the API. If thats the case it should be able to be reproduced on all version. but im not very familiar w application code :) 
Downloading now.

**Comment by vmuriart** [comment]
Partial success. It saved with no issues. Everything looked fine on my first test. On the second test, the new file saved, but Gisto isn't showing it after i switched back and forth between Gists. 
Closed and reopened, refreshed. Nada.
Logged into to my account on Chrome, file was there. Loaded on Gisto and it now shows up. I'll test it out some more later on, got a meeting. But so far it looks promising :+1:

**Comment by morsdyce** [comment]
Great, the issue with the file not appearing is because GitHub has a 60 second cache so it doesn't update correctly. I will make the changes to the local copy as well, so it should be updated.

**Comment by morsdyce** [comment]
I've started a new build that should solve that issue hopefully, I also removed the extra tracking.

**Comment by vmuriart** [comment]
Awesome, then the issue looks to be solved :+1: Thansk!

**Comment by vmuriart** [comment]
9e60d307afb9bc7b484a2d0339bd4bb78bb0ed4b was the fix?

**Comment by morsdyce** [comment]
Yes, along with https://github.com/Gisto/Gisto/commit/7fd19115acda29f43efd6dccea28ef6f06c8960d for modifying the local copy.

Glad to hear it works!

Thanks for pushing through with us to solve this :+1:

**Comment by vmuriart** [comment]
Our enterprise server got upgraded to the latest version from 2.0 (not 100% sure which version we were on, just know we were at 2.0 or less)
I tried to replicate the glitch on my other machine, and its not there anymore. Ultimately it depended on the enterprise server as well.

**Comment by morsdyce** [comment]
That's good to know, I suspected that is the case as we couldn't reproduce it with our enterprise server (which is at 2.1 i think).

Thanks for the update!
