### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by jeffrson** [Gisto/Gisto#178]
Hi,

I've got some issues with "sharing" gists. In the end, I intend to move some or all gists from one account to another.

1) I tried to share via E-Mail-Adress - this did not work (no message for recipient, no error for sender)
2) when I log out from one account, log in to another, it seems that the list of gists is not cleared (there are more and more Gists, which cannot be correctly accessed)
3) If a gist with a certain name exists (some old version), it will not be replaced by a gist with new content at the recipient. Also, there is no hint about an existing gist.
4) Unfortunately, comments are not shared with gists.

Furthermore, I've got some questions.
A) Is there a way to sort gists? Currently, the latest is always at the top of the list
B) Is there a way to export/backup all gists?

Hopefully, this is quite understandable - unfortunately I'm rather short of time, but don't want these notes to get lost.

Well, actually not all of this mail are bugs. I tried to send an e-mail to the address mentioned in the faq, but the mail returns as undeliverable.

Best regards

**Comment by sanusart** [comment]
Hey,

Regarding #1, you share by github username.

Now, are you using regular gisto or for enterprise?

Regarding backup, there is no option for backup or export at the moment. If
you only need to back them up you can use
https://www.npmjs.com/package/gist-backup

The rest we will need to check.

**Comment by ujaroe** [comment]
Thanks - I'm using regular GistoApp.

**Comment by sanusart** [comment]
Current Gisto version dropped support for sharing because lack of interest and will to maintain/pay for a server. What leaves Gisto completely server-less (with no 3rd party server except GitHub API) right now.
