### ISSUE TITLE
Groups / sharing feature

### ISSUE THREAD

**Issue by lrobeson** [Gisto/Gisto#180]
Any plans to add support for groups, similar to Gistbox?

**Comment by morsdyce** [comment]
It's something we're thinking about but is much harder for us as we want to stay server less as much as possible while there is no official support from github for teams.

We'd like to address it in the future once we can decide on how best this could be done.

**Comment by sanusart** [comment]
Current Gisto version dropped support for sharing because lack of interest and will to maintain/pay for a server. What leaves Gisto completely server-less (with no 3rd party server except GitHub API) right now. This may change in the future.
