### ISSUE TITLE
searching for multiple tags at the same time

### ISSUE THREAD

**Issue by openKadi** [Gisto/Gisto#181]
first of all congrats for this awesome app, it is a life saver.
I'm not sure if this is already implemented, I have some gists that are tagged with #jee and others with #servlets sometimes I need to find them at the same time, think of it like 

```
 SELECT gist FROM myGists WHERE tag='jee' OR tag='servlet' 
```

same issue I have is if I want to find a gist that has two tags like: if I have a document with #html #template I would like to find it by input of both tags to filter out the #html gists that dont have the #template tag think of it like

```
 SELECT gist FROM myGists WHERE tag='html' AND tag='template' 
```

thank you.

**Comment by sanusart** [comment]
Closing: exists starts from v1.9.61 (for now, few tags can be clicked on the dashboard and filter the search, later search bar version will be probably implemented too)
