### ISSUE TITLE
Dragging a file got open instead of creating new Gist in Windows

### ISSUE THREAD

**Issue by UberGruber** [Gisto/Gisto#182]
Hello there, 
fist of all thank you for your work and this amazing app, I already love it ;)
Unfortunately working with Windows (both 7 and 8.1) I noticed that if I drag a file into the app window the file is opened instead of creating a new gist on the fly. 

Below you can see a small video reproducing it (the cursor is captured but not the dragging icon).
http://sendvid.com/yjz60ozt

Is this intended, I'm missin something? 

Thank you!

**Comment by sanusart** [comment]
Hey,

I think only the new gist view meant to be drggged into.
[image: pasted1]

Is that works for you?
We should check and disable drag into unsupported areas.

**Comment by UberGruber** [comment]
Oh I see! 
Yes it's working, a bit inconvenient that I have to create a new git first and delete the default empty file, but absolutely minor nuissance, thank you for your time!

**Comment by sanusart** [comment]
Will be part of the next release. Also available via http://build.gistoapp.com/
