### ISSUE TITLE
auto-login with access token

### ISSUE THREAD

**Issue by glitsj16** [Gisto/Gisto#183]
Using two-factor authentication on github works well with Gisto, no complaints there. It would be even easier to use if Gisto had a commandline switch to start with ONLY the access token entree box visible. Or any other way to store a setting so users who have an access token for Gisto stored on disk could auto-login.  Is such a feature planned by the Gisto devs?

**Comment by miloskroulik** [comment]
Oh, that would be nice!

**Comment by morsdyce** [comment]
Sorry for the late reply.

I'm not sure we can do this with the constraints of node-webkit but I'll give it a check and see if its possible to do.

Thanks

**Comment by sanusart** [comment]
There's [command-line-arguments API](https://github.com/nwjs/nw.js/wiki/Handling-files-and-arguments#command-line-arguments), we could read token from an argument on start-up or from some specific file on the file system.

I've tested, args are passed to the app correctly.

What do you think?
