### ISSUE TITLE
Trend Micro Issue

### ISSUE THREAD

**Issue by jmreynolds** [Gisto/Gisto#185]
Hey guys, Trend Micro is flagging your software as malware - might want to take a look and resolve that.
[Last Scan.xlsx](https://github.com/Gisto/Gisto/files/135450/Last.Scan.xlsx)

**Comment by sanusart** [comment]
Thanks @jmreynolds, will check this out.

**Comment by sanusart** [comment]
Closing, no more reports and seem like temporary, isolated incident.
