### ISSUE TITLE
Ubuntu deb installer?

### ISSUE THREAD

**Issue by orschiro** [Gisto/Gisto#187]
Dear all, 

Thank you for your work on this great application!

Do you provide an Ubuntu deb installer?

Thankfully,

~Robert

**Comment by sanusart** [comment]
Hey Robert.

Sorry not at the moment. Do you have issues installing with generic Linux way?

**Comment by orschiro** [comment]
Hi Sasha,

Thanks for your quick response!

I always prefer using packages for my distributions.

That's why I was wondering whether someone had created deb packages already.

Bummer that this is not the case. :(

Warmly,

~Robert

**Comment by sanusart** [comment]
Hey,

Maybe someone did, we did not just yet. Though we started preparations for
building it, so we might integrate it into our release process in the near
future.

Thanks,
Sasha

**Comment by orschiro** [comment]
That is great news!

  

Could you leave a comment here once an official deb package is ready for
testing?

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Mar 29 2016, at 5:12 pm, Sasha Khamkov &lt;notifications@github.com&gt;
wrote:  

> Hey,  
  
Maybe someone did, we did not just yet. Though we started preparations for  
building it, so we might integrate it into our release process in the near  
future.  
  
Thanks,  
Sasha  
  
On Mon, Mar 28, 2016, 9:28 PM Robert Orzanna &lt;notifications@github.com&gt;  
wrote:  
  
&gt; Hi Sasha,  
&gt;  
&gt; Thanks for your quick response!  
&gt;  
&gt; I always prefer using packages for my distributions.  
&gt;  
&gt; That's why I was wondering whether someone had created deb packages  
&gt; already.  
&gt;  
&gt; Bummer that this is not the case. :(  
&gt;  
&gt; Warmly,  
&gt;  
&gt; ~Robert  
&gt;  
&gt; On Mon, Mar 28, 2016 at 7:18 PM Sasha Khamkov
&lt;notifications@github.com&gt;  
&gt; wrote:  
&gt;  
&gt; &gt; Hey Robert.  
&gt; &gt;  
&gt; &gt; Sorry not at the moment. Do you have issues installing with generic
Linux  
&gt; &gt; way?  
&gt; &gt;  
&gt; &gt; —  
&gt; &gt; You are receiving this because you authored the thread.  
&gt; &gt; Reply to this email directly or view it on GitHub  
&gt; &gt;
&lt;https://github.com/Gisto/Gisto/issues/187#issuecomment-202515277&gt;  
&gt; &gt;  
&gt;  
&gt; —  
&gt; You are receiving this because you commented.  
&gt;  
&gt;  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/Gisto/Gisto/issues/187#issuecomment-202518316&gt;  
&gt;  

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/Gisto/G
isto/issues/187#issuecomment-202947409)![](https://github.com/notifications/be
acon/AAKbw6VFhc0AMwJHJMAgcIx1G9IqWBtDks5pyUF5gaJpZM4H5qzq.gif)

**Comment by sanusart** [comment]
Sure thing. Not closing the issue.

**Comment by rhoconlinux** [comment]
Hi all!
I made a one-liner, ninja install until the .deb arrives! ;)
Tested on Ubuntu 14.04, the scritp works only in x64 systems. 

`cd /tmp ; wget http://download.gistoapp.com/Gisto-0.3.1-Linux_x86_64.tar.gz ; tar -zxvf Gisto-0.3.1-Linux_x86_64.tar.gz ; cd Gisto-0.3.1-linux_x64/ ; sudo ./setup`

Hope it serves, and cheers!

**Comment by orschiro** [comment]
Cool thanks @rhoconlinux! :)

Will this manual way ensure that I can update it once the official deb package is out?

~Robert

**Comment by rhoconlinux** [comment]
Well, @orschiro it will (of course) depend on how the .deb package is built. 

However, if the .deb is made following the same rules and locations than the "setup" script, then the answer is **yes**. 

:)

Cheers!

**Comment by JPvRiel** [comment]
I'd appreciate an apt repo please :-)

@orschiro, as a workaround for now, `checkinstall` ican help fudge custom install scripts or builds form source code into a debian package:
```
sudo checkinstall --install=no --fstrans=yes --exclude /lib --pkgname gisto --pkgversion=0.3.1 --nodoc ./setup
```

Then use the package manager
```
$ sudo apt-get install -f ./gisto_0.3.1-1_amd64.deb
```

*NOTE*: Sadly, checkinstall does bug out sometimes when handling symlinks, e.g. thinking `libudev.so.1` is affected because a symlink to it was made during the install script. so `--exclude /lib` helps avoid this issue below when installing:
```
pkg: error processing archive /home/a211278l/Installs/Linux/Gisto/Gisto-0.3.1-linux_x64/gisto_0.3.1-1_amd64.deb (--install):
 trying to overwrite '/lib/x86_64-linux-gnu/libudev.so.1', which is also in package libudev1:amd64 229-4ubuntu7
```

**Comment by orschiro** [comment]
>@orschiro, as a workaround for now, checkinstall ican help fudge custom install scripts or builds form source code into a debian package:

Thank you very much, @JPvRiel!

**Comment by JPvRiel** [comment]
@orschiro, don't thank me just yet. If you follow the checkinstall approach, I'd advise you overwrite the 'wrapper' script at `/usr/bin/gisto` with the following:
```
#!/bin/bash
exec -a "$0" "/opt/gisto/gisto-bin" "$@"
```

Worked for me - no need for the symlinking and `LD_LIBRARY_PATH` hackery...

**Comment by sanusart** [comment]
Exists starts from v1.9.61 (need testing).
