### ISSUE TITLE
Can I get this on Android?

### ISSUE THREAD

**Issue by CMCDragonkai** [Gisto/Gisto#189]
Feature Request.

**Comment by sanusart** [comment]
Do you mean as a 'viewer' or as fully functional Android app?

**Comment by CMCDragonkai** [comment]
There's lots of viewers. Would be great to have the ability to edit.

**Comment by sanusart** [comment]
Starting from v1.9.84 you can use webapp at https://web.gistoapp.com we will not develop native mobile client at this point as it is a very low demand.
