### ISSUE TITLE
Log-in failed - server responded with error

### ISSUE THREAD

**Issue by waldens** [Gisto/Gisto#198]
I googled, cannot find any solutions. Any suggestions?

![Screenshot](http://onuia4d7l.bkt.clouddn.com/2017_05_22_20170522021326.png)

**Comment by sanusart** [comment]
Hi. Is this your first login or you've used gisto before?

**Comment by waldens** [comment]
I used gisto before, and pause using it for a few months, and now pick it up again, and then see this error.

**Comment by sanusart** [comment]
I'd suggest clearing the app user directory to rule out old/expiered
authentication token issue.
What operating system are you running?

**Comment by waldens** [comment]
@sanusart  Win7x64，and thanks, problem solved!
