### ISSUE TITLE
Copy from Markdown interface

### ISSUE THREAD

**Issue by nitinsatish** [Gisto/Gisto#202]
I am not able to copy code from Markdown interface. It would be a good option since the raw text will have markdown formatting elements also.

I using the 64 bit Linux version of the app on Xubuntu 16.04.

**Comment by sanusart** [comment]
ref v2: 99d869d9d83aa843660b9a7b10c172f7520904f1

**Comment by sanusart** [comment]
Closing: exists starts from v1.9.61
