### ISSUE TITLE
Pressing Enter to "enter highlighted gist" doesn't work in the search box

### ISSUE THREAD

**Issue by Ghost4Man** [Gisto/Gisto#210]
When I'm **in the search box**, I can highlight a gist in the list with Ctrl+Down, but when I press Enter, **nothing happens**.
It works correctly only if I first click in the list, highlight some snippet, and then press Enter.
Version: 0.3.1 (Windows 64bit)

**Comment by sanusart** [comment]
Should work using tab navigation in v1.9.78 and on.
