### ISSUE TITLE
Feature Request - Shareable link button

### ISSUE THREAD

**Issue by chaoscreater** [Gisto/Gisto#226]
Hi there,

Is it possible to add a button that generates a shareable link to a private gist?

**Comment by sanusart** [comment]
@chaoscreater there are two of them, it works the same for private and public.
<img width="1037" alt="gisto_v1_10_7_ _development_ _and_developer_tools_-_file____users_sasha_www_gisto-and-co_gisto_dist_index_html" src="https://user-images.githubusercontent.com/267718/46637884-d5de0480-cb66-11e8-99e2-1b983b312ce2.png">
