### ISSUE TITLE
no syntax highlighting

### ISSUE THREAD

**Issue by xgdgsc** [Gisto/Gisto#231]
**Describe the bug**
I get no syntax highlighting in gisto.

**To Reproduce**
1. Go to any code snippet

**Expected behavior**
  syntax highlighting should work for the languages

**Screenshots**
 
![image](https://user-images.githubusercontent.com/1189869/47419848-a7d80180-d7af-11e8-8d6e-2a9db069faaf.png)

**Desktop app (please complete the following information):**
 - OS:  ubuntu 18.04
 - Version 1.10.10 appimage

 
**Additional context**
I' m using the appimage and I tried various themes and code types and none of them show syntax highlighting, except a markdown file.

**Comment by sanusart** [comment]
@xgdgsc are you experiencing same lack of highlighting when browsing same snippets via the web client (https://web.gistoapp.com)?

**Comment by xgdgsc** [comment]
I click the Login with github button on the web and has no effect.
