### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by chaoscreater** [Gisto/Gisto#234]
Not sure if this is a bug or just me, but when I click on the lightning update icon, it used to download the update for me. Now, it doesn't do anything when I click on it and I have to manually go onto Github to download the latest release...

**Comment by sanusart** [comment]
What OS you use? And what is the current Gisto version runs on your machine?

**Comment by chaoscreater** [comment]
I use Windows 10 build 1809 (latest). Was running Gisto v1.10.9

**Comment by sanusart** [comment]
Please try to update again, there is some issue with .blockmap file for EXE generated by the electron builder. I've removed it, so It should be able to update properly now. Thanks!
