### ISSUE TITLE
Gisto v1.10.26, and above, is very slow

### ISSUE THREAD

**Issue by charlwillia6** [Gisto/Gisto#244]
**Describe the bug**
Navigating in Gisto is very slow.  

**To Reproduce**
1. Open Gisto
2. Click on anything
3. It's slow and sometimes becomes completely unresponsive.

Especially if the API rate limit display is enabled.  Additional settings like Code lens, Minimap, and Format on Type make it even slower.  However it is extremely slow even without these enabled.  I am pretty sure the cache isn't working because it acts as though it is pulling from GitHub on every single click.

What is strong is that it seems fast when you first open it.  And it gets slower and slower after that.

**Expected behavior**
I expect it to not be slow and become unresponsive

**Desktop app (please complete the following information):**
 - OS: Windows 10
 - Version 1.10.26 and 1.10.27.beta

**Additional context**
This isn't just a "little" slow.  So slow it makes it almost useless to use for me.  I used the old versions of Gisto and the new version definitely is an upgrade in features and design, but the old version worked much better.  I was using Lepton recently and Gisto has a lot more features but Lepton is fast.  Like super fast compared to Gisto.  I really want to like it.  But everything is so slow.

**Comment by sanusart** [comment]
Thanks for reporting!

Sorry to hear that. Sounds serious, I'll check it out.
Where you using it with same intensity prior to 1.10.26? Was it the same or is it something that you've noticed after 1.10.26?

**Comment by sanusart** [comment]
Could you please check if https://github.com/Gisto/Gisto/releases/tag/v1.10.27-beta.1

Fix it for you?

**Comment by sanusart** [comment]
Should not be slow now. Please reopen if any issue still exist.

**Comment by charlwillia6** [comment]
@sanusart - I only tested this for about 15 minutes, but yes, it is definitely faster.  A LOT faster.  

Thank you so much for the fast turn around on this.  I will let you know if after continued use if any issues arise.
