### ISSUE TITLE
Can't type in new created snippet

### ISSUE THREAD

**Issue by szyn33k** [Gisto/Gisto#245]
**Describe the bug**
Can't type in editor when creating new snippet. 
I'm logged at my github account. I try add new private snippet.

**To Reproduce**
1. Click on 'New Snippet'
2. Click on 'Add file'
3. Try type in editor

**Screenshots**
![Przechwytywanie](https://user-images.githubusercontent.com/25787891/54200867-9e380780-44cc-11e9-8d39-306943379531.JPG)

**Desktop app (please complete the following information):**
 - OS: Windows 10
 - Version: v1.10.27

**Comment by dennybaa** [comment]
same on ubuntu 18.04

**Comment by sanusart** [comment]
Thanks for reporting, this looks like regression from last bug fix when editor is readonly unless it is in edit mode. Will release new version with bug fix tonight.

**Comment by dennybaa** [comment]
@sanusart Thank you for the awesome application and support :bowing_man:

**Comment by sanusart** [comment]
Should be fixed in v1.2.28
