### ISSUE TITLE
Use international font for rendering gists names

### ISSUE THREAD

**Issue by sergeevabc** [Gisto/Gisto#246]
Oh well, another app whose developer neglects non-Latin users. That’s why inscriptions in Latin alphabet are rendered with sans-serif, and the rest are rendered with some serif fallback.

![1]

[1]: https://images.vfl.ru/ii/1553090546/555902a0/25845540.png

**Comment by sanusart** [comment]
Hi, I am deeply sorry to be another of this developers. 
**But** taken this app is free and open source, I see no reason for other developers who use non-Latin languages to assist internationalise it. 
Or at least provide constructive feature request via issues.

**Comment by sergeevabc** [comment]
Сань, достаточно взять шрифт из библиотеки Гугла, например, Roboto или Noto Sans, и будет всем счастье.

**Comment by sanusart** [comment]
It is not that. It is the tone that request made that shutters every
ambition to even work on it :/

**Comment by sergeevabc** [comment]
Сань, надо понимать, что плюнув в душу половине мира, которая в гробу видала английский, половина мира может возмутиться. И я ещё внятно объяснил, в чём прокол и как его быстро исправить. Если же уязвлённое самолюбие дороже истины и есть иллюзия, что бесплатностью можно оправдать любую глупость, то лучше не показываться на людях, а программировать где-нибудь в пещере.

**Comment by sanusart** [comment]
I am not here to deal with your point of view on the outside world and
definitely not pushing you to use this tool. While it is great you've
decided to enlighten me with your wisdom of how emotional stability may
harm certain processes, this is not a way to suggest a feature you want in
that certain tool.
Now it is time to crawl to that cave you've mentioned.

**Comment by sanusart** [comment]
Should be OK in >=v1.11.0
