### ISSUE TITLE
How to change syntax highlighting

### ISSUE THREAD

**Issue by szyn33k** [Gisto/Gisto#248]
**Description**
I added 3 file with .sql extension. First has SQLPL syntax, second has PLpgSQL, third has SQL.
And only with SQL syntax has code highlighting. Every file has correct Firebird SQL code.

Can i change syntax manually?

**Screenshots**
https://i.imgur.com/TA9dA3b.jpg

**Desktop app (please complete the following information):**
 - OS: Windows 10
 - Version - 1.11.0

**Comment by sanusart** [comment]
This is probably a bug with language mapping. I'll take a look tonight. 
Thanks for reporting.

**Comment by sanusart** [comment]
This was the reproducible gist: https://gist.github.com/sanusart/c569bf899615302028112e25097b5191

**Comment by szyn33k** [comment]
I updated Gisto but still have 3 different syntaxt. How can i change it?

**Comment by sanusart** [comment]
@szyn33k Github is detecting syntaxes and I use that to match highlighter. It is not file extension based, it is file type based.

As in your screenshot - github detected 3 different flavours of SQL even though their file extensions are the same.

![image](https://user-images.githubusercontent.com/267718/55100503-ae560680-50ca-11e9-8817-09b262efd942.png)

Is that a problem?

**Comment by sanusart** [comment]
Please feel free to reopen if you think it is still an issue.
