### ISSUE TITLE
Sort snippets

### ISSUE THREAD

**Issue by szyn33k** [Gisto/Gisto#249]
Can you add feature that allows manually sort snippet on list?

https://i.imgur.com/7tJoyVi.jpg

**Comment by sanusart** [comment]
@szn33k meaning to add ability to sort by name and not by date (latest first) as it is now?

If that the case then sure. No problem.

**Comment by szyn33k** [comment]
@sanusart yes, exactly. I would like to sort snippets by name. But maybe you can do drag and drop sort? It would be amazing.

**Comment by sanusart** [comment]
@szyn33k Cool. Will add sort by...

Unfortunately drag and drop sorting will requere to save the custom sort order somewhere in a centralised storage (server), and we have no server (by design) to keep it there.

**Comment by szyn33k** [comment]
@sanusart Ok, i understand. So by now sort by name would make me happy :)

**Comment by sanusart** [comment]
Controlled via settings:
![image](https://user-images.githubusercontent.com/267718/55655469-02fd2e00-57fd-11e9-85ab-639b72f8990d.png)
