### ISSUE TITLE
Latest version lags a lot

### ISSUE THREAD

**Issue by chaoscreater** [Gisto/Gisto#252]
On v1.12.1, I cannot create a new snippet and add a file. If I try adding a filename, or anything in the file contents (where the script goes), it lags. It's so laggy to the point that it's unuseable. 

API rate limit is 4987/5000, so nothing wrong with my Github account. 

Have tested and verified issue on 2 different machines, one running on Windows 10 1803 and the other on Windows 10 1607.

If I downgrade to 1.11.3, everything is fine again.

**Comment by chaoscreater** [comment]
Sorry, just re-opening this one. Still getting lag in all of the text fields when creating a snippet.

**Comment by sanusart** [comment]
Will check that out. We are talking about the latest v1.12.2 I assume.

**Comment by chaoscreater** [comment]
Thanks! And yup, I'm always on the latest version :)

**Comment by sanusart** [comment]
@chaoscreater I cannot reproduce the lag in the current version. Can you maybe specify your flow in a more detailed way?

**Comment by chaoscreater** [comment]
Sure thing.

So I simply create a new snippet and in any of the text fields (description, filename, edit window), it lags if I input something in there.

![image](https://user-images.githubusercontent.com/18227319/60627185-69680b80-9e41-11e9-8c43-d385ddf79a7e.png)

Here are my settings:

![image](https://user-images.githubusercontent.com/18227319/60627225-84d31680-9e41-11e9-9057-b74712468357.png)

![image](https://user-images.githubusercontent.com/18227319/60627209-7ab11800-9e41-11e9-9c8e-b2a63b9a8704.png)

**Comment by sanusart** [comment]
Hmm. Still not able to get a lag. Is that a Linux? What distro?

**Comment by sanusart** [comment]
@chaoscreater Found it :) v1.12.3 just released - should fix the issue.
