### ISSUE TITLE
Formatting on newly created snippet

### ISSUE THREAD

**Issue by chaoscreater** [Gisto/Gisto#253]
I'm on v1.12.2.

When I'm creating a new snippet, the formatting looks correct. But as soon as it is saved, the formatting disappears, as if the formatting is for a .text file.

![image](https://user-images.githubusercontent.com/18227319/59396403-bcb7e280-8ddc-11e9-9f4b-c70972bb804f.png)

**Comment by sanusart** [comment]
File with no extension defaults to text file. This is expected behavior.
