### ISSUE TITLE
Make the edit window larger

### ISSUE THREAD

**Issue by chaoscreater** [Gisto/Gisto#254]
Is it possible to customize the size of the edit Window during the creation of a new snippet? There is a lot of wasted space between the edit window and the "Add file" button. And it would be nice if some fields at the top can be shrunk to a smaller size.

**Comment by sanusart** [comment]
Hey could you highlight the waisted space on a screenshot or something, to
get a better idea of the exact area in question?

Thanks.

**Comment by chaoscreater** [comment]
Hi there,

So basically just the circled areas in the screenshot. I would like to shrink them if possible.

![image](https://user-images.githubusercontent.com/18227319/60470921-61c82b80-9cb6-11e9-84f9-0c49f10fbe00.png)

**Comment by sanusart** [comment]
I see. Agree. Will see how I can make most of the space, probably by making the fields and buttons a side bar.

Thanks!

**Comment by chaoscreater** [comment]
Hi again!

I love the new layout, but the edit window is still tiny. Is it possible to make this larger? Just need to use the extra space below it:

![image](https://user-images.githubusercontent.com/18227319/60776462-90e01080-a180-11e9-8974-e29a751be99f.png)

**Comment by sanusart** [comment]
Hey. Yes. I had no big screen an I see a view issues more on that
screenshot. Will correct in next version. Thank you.
