### ISSUE TITLE
Open links in the default web browser

### ISSUE THREAD

**Issue by dotherightthing** [Gisto/Gisto#256]
**Is your feature request related to a problem? Please describe.**

I find it creepy that links in my Markdown files open in a new Gisto window/webview. I'd much prefer them to open in my default web browser.

**Describe the solution you'd like**

Clicking a link launches my default web browser and loads the URL.

**Describe alternatives you've considered**

An option to toggle between the Gisto browser and my default browser would also be acceptable.

I tried right-clicking the link to copy the URL, but right-clicking has been disabled (also creepy).

**Additional context**

Screenshot of a link that has opened in the Gisto browser:

![markdown-link-open-in-gisto-browser](https://user-images.githubusercontent.com/638871/63138346-4038be80-c02e-11e9-9fec-55e259bf321d.png)

**Comment by sanusart** [comment]
Hey what version and what OS?

**Comment by dotherightthing** [comment]
Sorry,

* Gisto 1.12.8 (1.12.8.791)
* MacOS Sierra 10.12.6

**Comment by sanusart** [comment]
Thanks @dotherightthing,
Can you share the gist by any chance (or at least a copy of it with a link in markdown that behaves like that) cannot reproduce in this version.

**Comment by dotherightthing** [comment]
@sanusart Sure, it's https://gist.github.com/dotherightthing/517fec9c6218aaf9288f508a2a632fc2

**Comment by sanusart** [comment]
@dotherightthing Thanks. 
I forked it and all seem to be fine. Any chance you holding the `cmd` key while clicking it?

**Comment by dotherightthing** [comment]
@sanusart Oh, right. Yes, I was holding down the command key, seems that it's an automatic reflex for me ;-)
