### ISSUE TITLE
Some snippets are not saved

### ISSUE THREAD

**Issue by tobycheese** [Gisto/Gisto#257]
When editing some of my snippets and then clicking save, the edits are not being saved and the snipped stays as it was before the edit. While doing this, the API rate limit count briefly goes down, then back up to where it was before the click on save. If I edit the gist on github directly, the edit is correctly reflected in gisto.

However, I can create new snippets just fine. I can also edit those new snippets just fine. The problem happens only with some snippets, other (older) snippets work.

I realise that if you can't reproduce this, it's going to be hard to pinpoint. I am willing to help if you instruct me.

OS: MacOS Mojave 10.14.5
Gisto Version: 1.12.8.791, desktop version

**Comment by sanusart** [comment]
Is it possible for you to prepare some public gist I can test on with the changes that trigger the error?

**Comment by tobycheese** [comment]
[Here](https://gist.github.com/tobycheese/d218cc77b86c2875b1d62202a27d756f) is one. Edits I do on it with Gisto Desktop are not saved (verified after making it public).

**Comment by sanusart** [comment]
Reproduced, thank you. Looks like some issues with underscores and dashes in file name. Fill fix asap. Thanks for reporting and creating a test case.

**Comment by sanusart** [comment]
Will be available in next release (v1.12.9) in a few moments
