### ISSUE TITLE
Small gists take up unnecessary space

### ISSUE THREAD

**Issue by jbhanks** [Gisto/Gisto#258]
In my Gisto install, even very short snippets take up a full page, thus creating a lot of blank space.  On the GitHub website, this is not the case, and space is not wasted on blank lines.
 Screenshots here: [https://imgur.com/a/yObcB4b](url)

I'm not sure if this is a bug or just how Gisto is designed, but it would be nice if it didn't waste all that space.

**Comment by sanusart** [comment]
This is actually limitation of editor used in gisto. Will keep open for a better days (when will have time capacity for testing age cases if implemented some custom solution for line count sizing).

**Comment by jbhanks** [comment]
That's too bad :( It makes for a lot of unnecessary scrolling, which makes Gisto less convenient to use.

**Comment by sanusart** [comment]
@jbhanks Would you be interested to help test pre-realease version if it?

**Comment by sanusart** [comment]
Available in v1.12.10
