### ISSUE TITLE
Fade out Texts are very annyoing...

### ISSUE THREAD

**Issue by schittli** [Gisto/Gisto#259]
**Thank you very much for this great Tool!,**
it's strange that GitHub did not think about this kind of SW.

#### Describe the bug
For example, a Gist Title is displayed using a fade out color scheme, so that the last ~15 characters are are less and less readable.

**This is very annoying**, because if there is more Text (anywhere, not only in a Title), then it usually makes sense for it to be there. Therefore, it does not make any sense to hide it just to look 'cool'.

In context, any average user will recognize that a text has been truncated, even without optical tricks.

At least, it should be possible to disable this effect.

#### To Reproduce
1. Open Gisto
2. Select any Gist with a long title
3. Are you able to read all the text which could be displayed? 
The Title is shortened, although it could be displayed on the screen.

#### Expected behavior
At least, this effect should be deactivatable
If the screen is able to display any text, then it should be fully readable. 
If an optical trick is absolutely necessary, then please use the `…` character.

#### Screenshots
![image](https://user-images.githubusercontent.com/8282673/65814276-ee17bb00-e1df-11e9-9f11-9f53dc569157.png)

#### Desktop app (please complete the following information):
 - OS: Windows
 - Version 1.12.11

**Comment by sanusart** [comment]
@schittli agree, will revisit title truncation.

**Comment by schittli** [comment]
Thank you very much for changing this behaviour, 
I am quite surprised that CSS offers such a nice solution.
