### ISSUE TITLE
mobile App planned (Android,iOS,..)? #Feature Request

### ISSUE THREAD

**Issue by IngoTested** [Gisto/Gisto#260]
** Gisto is working great for PC'S  but a working mobile app is missing **
there are only 2 viewer gisto Apps for Android available, for iOS ican say nothing.

** A mobile App for Android**
A mobile app , which search public and own secret gists and can create new gist per paste in an edit field.

** Alternative for mobile gists there are nothing for now*
Only if not using pastbin.com instead Github Gist.

** existing mobile Apps for GitHub Gist**
[GithubGist](https://play.google.com/store/apps/details?id=com.githubgist)
that seem not working only browsing public gists.

[Gist-A-Viewer](https://play.google.com/store/apps/details?id=com.jldubz.gistaviewer)
I have not tested it but it described as viewer

**Comment by IngoTested** [comment]
Sorry I don' tknow how i could add a label for Feature Request.

**Comment by sanusart** [comment]
You can run https://web.gistoapp.com on any tablet I think. Phones resolution won't go. 
There is no iOS or Android app simply because they request payment to get listed in their store.
