### ISSUE TITLE
portable Gisto App doens't doesn't start at NightlyBuild 20170306 or newer

### ISSUE THREAD

**Issue by IngoTested** [Gisto/Gisto#261]
**Describe the bug**
Every portable Gisto since 20170306 will fail on starting the app
![image](https://user-images.githubusercontent.com/56210207/66708217-45279f00-ed4d-11e9-9eab-241345858f4c.png)
4 processes will shown in task manager, but the app will not start .

**To Reproduce**

1. Follow the step as described in th FAQ https://www.gistoapp.com/faq#run-as-portable
2. After starting the gisto.bat  the Folders **gistoData,locales** will be created and the task manager shows 4 gisto.exe processes but no window will. After 20 minutes no change. 
3. killing the task and repeat start of gisto.bat (with delete Folders **gistoData,locales** or no delete ) shows the same behaviour.
![image](https://user-images.githubusercontent.com/56210207/66708361-abadbc80-ed4f-11e9-9b73-2eb65b9bc8a4.png)

**Expected behavior**
the Folders **gistoData,locales** should be created and after a few seconds the Window of Gisto should shown.

![image](https://user-images.githubusercontent.com/56210207/66708381-fdeedd80-ed4f-11e9-910f-389675b3e78a.png)

**Screenshots**
Tasmanager shows the 4 gisto-processes.
![image](https://user-images.githubusercontent.com/56210207/66708424-8a010500-ed50-11e9-9fdc-aad6aa2ea42c.png)

To repeat the start procedure kill the tasks per cmd line.
![image](https://user-images.githubusercontent.com/56210207/66708457-f4b24080-ed50-11e9-8de2-bff69c441407.png)

**Desktop app (please complete the following information):**
 - OS: Windows 7
 - Version : Nightly Build from 20170306 to 20180307
e.g. gisto-20180307-win-x64.zip

**Web app (please complete the following information):**
 - OS: Windows 7
 - Browser chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit), Firefox 60.9.0esr (64-Bit)
 - Version [V1.12.12]

**Additional context**
The problem is similar as described here but  mention version will  not fit.
https://github.com/Gisto/Gisto/issues/221

**Comment by sanusart** [comment]
Same as #262.
