### ISSUE TITLE
strange behaviour on 2nd Github account on Login-Action

### ISSUE THREAD

**Issue by IngoTested** [Gisto/Gisto#262]
**Describe the bug**
strange Login behaviour on portable App Gisto on 2nd Account.

1. Web-App & portable App will not let you login with user and password authentification.
2. some other  versions than  gisto App V 0.2.6b  only git let you only log  in with github login or token
3. some other  nightly build versions than  gisto App V 0.2.6b  only git let you only log  in with github login
4. gisto App V 0.2.6b will only allow to login if user+password and additional token is authentificated.

**To Reproduce**

1. Follow the step as described in th FAQ https://www.gistoapp.com/faq#run-as-portable
2. After starting the gisto.bat  the Folders **gistoData,locales** will be created and the task manager shows 4 gisto.exe processes but no window will. After 20 minutes no change. 

1. or install a release version and start it

**Expected behavior**
In should possible to login in 3 ways:

username + password 
token
login with GithubLogin

in the application settings in GitHub should be stored following automatic:

![image](https://user-images.githubusercontent.com/56210207/66708778-85d7e600-ed56-11e9-8b42-7b58616b179a.png)

it this stoken should auto added :

![image](https://user-images.githubusercontent.com/56210207/66708741-d13dc480-ed55-11e9-8862-5b7c3c6e5f2f.png)

**Screenshots**

**Desktop app (please complete the following information):**
 - OS: Windows 7
 - Version : different working version

**Web app (please complete the following information):**
 - OS: Windows 7
 - Browser chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit), Firefox 60.9.0esr (64-Bit)
 - Version [V1.12.12]

**Additional context**

More details (Version behavior  and mored detail for steps to reproduc will follow in the next days.
eventually i create a clean githubAccount to see if a 2nd account is the problem my 2nd account has a problem.

**Comment by sanusart** [comment]
Hey, sorry yo some how got to the legacy version of gisto. I'll update the
website FAQ area to reflect that.
Regarding the portable app, will have to see how it is done. Will update.

**Comment by sanusart** [comment]
Closing in favour of #263
