### ISSUE TITLE
Lag v1.12.12 [Windows 10 Home - 64bit]

### ISSUE THREAD

**Issue by WebSpectrum** [Gisto/Gisto#265]
I'm getting a lot of lag and performance issues, is anyone else experiencing the same?

**To Reproduce**
1. add a new gist
2. or edit an existing one
3. when typing input has a few seconds of lag before updating
4. 

**Expected behavior**

**Screenshots**

**Desktop app (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.10.1]

**Web app (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, Firefox, safari, ...]
 - Version [e.g. 1.10.1]

**Additional context**

**Comment by sanusart** [comment]
Current latest version is v1.12.13
