### ISSUE TITLE
Crash when searching "c++"

### ISSUE THREAD

**Issue by ds-georgiev** [Gisto/Gisto#270]
**Describe the bug**
When in the search box you type c++ the program crashes.

**To Reproduce**
1. Input c++ in the search bar

**Expected behavior**
I was expecting to show me C++ as a listed language but got an empty blue screen

**Desktop app (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version  v1.12.13

**Comment by sanusart** [comment]
Reproduced on a dashboard filter searches.
Main search acts correctly.
