### ISSUE TITLE
Release 1.12.14 does not have a Mac version?

### ISSUE THREAD

**Issue by tjluoma** [Gisto/Gisto#273]
I'm looking at <https://github.com/Gisto/Gisto/releases/tag/v1.12.14> but don't see a Mac build version (usually a .zip) listed.

Was that just an oversight or did Mac get dropped for some reason?

**Comment by sanusart** [comment]
@tjluoma 
It is still being deployed:
![image](https://user-images.githubusercontent.com/267718/74374467-26164800-4de7-11ea-83f5-9ca45a356a34.png)

**Comment by sanusart** [comment]
It is there now: https://github.com/Gisto/Gisto/releases/tag/v1.12.14 :)

**Comment by tjluoma** [comment]
Awesome! Now that's fast service ;-)
