### ISSUE TITLE
Add required token permissions to documentation

### ISSUE THREAD

**Issue by ScottJWalter** [Gisto/Gisto#276]
**Is your feature request related to a problem? Please describe.**
Less a problem and more a frustration:  While you can use a Github access token (instead of giving it your un/pw and have them create one for you), there's no place in the documentation that explicitly identifies what permissions are needed should you choose to create the token yourself.

**Describe the solution you'd like**
A clear list in the documentation that states something to the effect that "... to create your token, follow the instructions on Github and make sure the following permissions are selected: ..."

**Describe alternatives you've considered**
Alternatives are to either:  a) use un/pw (and trust the company.  No insult intended, folks.), or b)  guess what permissions are needed (trial and error).

**Additional context**
Fortunately, it _seems_ that the only required permission is "create gists".  If, in fact, that's the case, it would _really_ be nice to know that (to avoid excessive over-granting).

**Comment by sanusart** [comment]
Thanks for the feedback and suggestion, indeed currently only "Create Gist" permission needed to fully utilise it.
Will add that bit into documentation and maybe above the screen of the token input.

Thanks!
