### ISSUE TITLE
Allow for editing the title of a gist

### ISSUE THREAD

**Issue by ScottJWalter** [Gisto/Gisto#277]
**Is your feature request related to a problem? Please describe.**
Not a problem, but when (for example) wanting to tag an existing gist for better organization in Gisto, it would be nice not to have to leave Gisto to accomplish it.

**Describe the solution you'd like**
An additional field on the "edit gist" page that allows for editing the gist title.

**Describe alternatives you've considered**
The alternative is to open the gist in your web browser so you can edit the title on Github, then go back to Gisto and force a refresh to get it to load the updated metadata.

**Comment by sanusart** [comment]
There is no?
![image](https://user-images.githubusercontent.com/267718/76256571-d8abc000-6258-11ea-9da0-bff0f7d7817d.png)

**Comment by ScottJWalter** [comment]
You gave me an idea, which lead to this discovery.  There's a browser width boundary, below which you see the title in edit mode:

![web gistoapp com_1](https://user-images.githubusercontent.com/205537/76427159-f755a800-6379-11ea-87a8-cd0d63b756e6.png)

If you go over the width boundary, you get:

![web gistoapp com_2](https://user-images.githubusercontent.com/205537/76427226-09cfe180-637a-11ea-81cd-d5601f8be134.png)

and the title is no longer editable (or visible).

**Comment by sanusart** [comment]
👍 Got it!
You using it as a web app, right, not on the desktop?

I think removing the ellipsis should be the way to go.

**Comment by ScottJWalter** [comment]
Correct (sorry).  I'm accessing via the web app interface.

**Comment by sanusart** [comment]
Why sorry, all good. 
I am asking because on the desktop the behaviour is a bit different, there is minimum width for the window. 

Thanks for the feedback~

**Comment by ScottJWalter** [comment]
That would explain it.  You're welcome.

**Comment by sanusart** [comment]
Should be fixed now.
