### ISSUE TITLE
All Client Validation Failed Error 422 

### ISSUE THREAD

**Issue by reki-cool** [Gisto/Gisto#282]
**All Client Validation Failed Error 422 **
I can login to my Gisto client with my github account.
however i get a error "Validation Failed Error Code 422 " when I create a new snippet.

**Screenshots**
![image](https://user-images.githubusercontent.com/36763837/79294011-aea88600-7f07-11ea-8a81-19767bfbd22b.png)

**Desktop app 
 - OS: Windows 10
 - Version 1.13.2

**Web app 
 - OS: Windows 10
 - Browser chrome
 - Version 1.13.2

**Comment by sanusart** [comment]
Hey. This probably means GitHub API is not happy about the content or tile
of the gist.

If the text of the gist can be posted in public here I'd be happy to
investigate.

**Comment by reki-cool** [comment]
Successfully solved my problem, thanks
