### ISSUE TITLE
Showing Full Tag Text (either on Mouse Hover or as an option to change or fit width)

### ISSUE THREAD

**Issue by bbruman** [Gisto/Gisto#294]
Great app, love it.

Only gripe is how small the Tags are and how it cuts off the text without anyway to view the full tag without searching specifically for it.

![image](https://user-images.githubusercontent.com/18406617/90281357-69a34a80-de3a-11ea-8a6f-bc9bf2fd730c.png)

Example above is for the tag `woocommerce`

Now I was trying to add another tag `woocommerce_checkout_billing` -- a woocommerce filter action.

Another example `woocommerce_gateway_icon` -- again another woocommerce filter action

As of now each of these tags will appear as the image I provided above, with no way to distinguish between tags that start with the same word/letters.

Probably an easy solution would be just to show the full tag on mouse hover.
Or perhaps an option not to cut off tag text?

Just some way to decipher between the tags without having to remember them or going through a few loops/clicks to find what tag you're looking for.

Thank you!

**Comment by sanusart** [comment]
If you create tags with no underscore it will brake into lines.
![image](https://user-images.githubusercontent.com/267718/95113177-b6284980-074a-11eb-8d99-39cb1e43bb06.png)

I guess we can also replace underscores for tag presentation (just not sure this is desired for all).

**Comment by sanusart** [comment]
Adding to show full text on hover to next release
