### ISSUE TITLE
gisto vs. gist.

### ISSUE THREAD

**Issue by hongyi-zhao** [Gisto/Gisto#299]
I noticed that there are several gists-relevant tools, say, the following ones:

https://github.com/defunkt/gist
https://github.com/Gisto/Gisto

Which is more powerful and feature-rich for this sort of job?

Regards,
HY

**Comment by sanusart** [comment]
Hi. The are very different. 
The first one is a command line utility, the second one is an desktop and web application with user interface.

**Comment by hongyi-zhao** [comment]
> Hi. The are very different.
> The first one is a command line utility, the second one is an desktop and web application with user interface.

But they have the same purpose, i.e., facilitating the publishing and management of gists.

**Comment by sanusart** [comment]
Yes. That is correct.
